name: Metrics
on:
  schedule: [{cron: "0 2 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: Abhinav-ranish
          template: classic
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}

          # Good defaults
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_followup: yes
          plugin_followup_sections: repositories
